### ISSUE TITLE
Add/Test airflow-with-kerberos

### ISSUE THREAD

**Issue by sodre** [conda-forge/airflow-feedstock#13]
https://github.com/conda-forge/airflow-feedstock/blob/b9abae3415a42a470dfd690c66a5bfab9451c9be/recipe/meta.yaml#L213-L223

**Comment by xylar** [comment]
I added `airflow-with-kerberos` in #47.  However, the dependency on `snakebite` is problematic, since `snakebite` only supports python 2.7 and we no longer build `airflow` with python < 3.6.  So I am leaving this open until we can figure out how to get a working install.

**Comment by xylar** [comment]
This package should be available in the next release, but may not be very useful: https://github.com/apache/airflow/pull/10865

**Comment by xylar** [comment]
I think the approach in 2.0.0 will be different enough that we can revisit this via the new provider approach.  I'm closing this for now.
