### ISSUE TITLE
anaconda.org has no record of any package by the name "google-cloud-dataflow"

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/airflow-feedstock#15]
https://github.com/conda-forge/airflow-feedstock/blob/b9abae3415a42a470dfd690c66a5bfab9451c9be/recipe/meta.yaml#L177

**Comment by sodre** [comment]
I wonder how that passed the build test...I'm looking into it now.

**Comment by kalefranz** [comment]
No problem for me. Was just running consistency checks again conda-forge and came across these two issues :)

**Comment by jakirkham** [comment]
Thanks for checking things out Kale. Were there any other issues? Are these checks scripted (and possibly shareable)?

**Comment by kalefranz** [comment]
I’ll be sharing everything soon, yes :)

**Comment by kalefranz** [comment]
FWIW, as a preview, I think the biggest problem I found is with `itk`. The package started out as the C library itk.  Then it was renamed to `libitk`, but the original `itk` packages still exist.  Then the `itk` package got taken over by duplicating the `itk` wheel into a conda package, which doesn't depend on `libitk` and embeds all the C libs in `site-packages`.

This is the only example I think I've ever seen where the contents of a particular package name within a channel shifted so dramatically.  Once a package name is used within a channel, the primary purpose/contents of that package name probably shouldn't ever be used for something else.

More to come... I have several things to document and write up as foundation for all the details.

**Comment by xylar** [comment]
We no longer have any build with `google-cloud-dataflow` as a dependency so I think this can be closed.
