### ISSUE TITLE
Add/Test airflow-with-hive

### ISSUE THREAD

**Issue by jkornblum** [conda-forge/airflow-feedstock#22]
https://github.com/conda-forge/airflow-feedstock/blob/b9abae3415a42a470dfd690c66a5bfab9451c9be/recipe/meta.yaml#L192-L199

**Comment by jkornblum** [comment]
airflow's hive_hooks.py also requires `hmsclient`, version 0.1.1 works. Its a module level import.
`hmsclient` is not available on conda-forge or defaults channel

**Comment by xylar** [comment]
We are not currently able to support `airflow-with-hive` because there is no feedstock for the `hmsclient` dependency.

**Comment by xylar** [comment]
I am adding a request for a feedstock for `hmsclient`: https://github.com/conda-forge/staged-recipes/pull/12234
