### ISSUE TITLE
Update to support Airflow 1.10.2 & Airflow 1.10.3

### ISSUE THREAD

**Issue by OmerJog** [conda-forge/airflow-feedstock#28]
The repo is 2 releases behind.
Only 1.10.1 is available.

**Comment by xylar** [comment]
I'm working on this (#27 and #29) but it's a huge pain.  Airflow depends on rather old versions of a bunch of packages that haven't been built for python 3.7:
* alembic < 0.9
* lxml >=3.6.0,<4.0
* tenacity==4.8.0
* flask-swagger==0.2.13
* tabulate>=0.7.5,<0.8.0

Each of these requires making a pull request to the respective feedstocks with a new build of this old version, and requesting that the maintainers merge it.  This is going to take awhile.  Feel free to chip in...

**Comment by xylar** [comment]
See #29 for my progress.

**Comment by xylar** [comment]
These versions are available for python 2.7 and 3.6.  Python 3.7 support should be easy to add soon, just waiting on the dependencies to make their way to the anaconda channel.
