### ISSUE TITLE
Bug with Authentication-password

### ISSUE THREAD

**Issue by jpoullet2000** [conda-forge/airflow-feedstock#3]
There is a bug with the [linux-64/airflow-1.8.0-py35_1.tar.bz2](https://anaconda.org/conda-forge/airflow/files) when using classical password authentication
```
[webserver]
authenticate = True
auth_backend = airflow.contrib.auth.backends.password_auth
```
The reason is that it uses flask-login 3.2 which has transformed a few methods (like is_authenticated()) into properties (is_authenticated). 
Solution: use flask-login **2.11** as it is done in airflow setup.py

**Comment by jpoullet2000** [comment]
FYI, [here](https://anaconda.org/jpoullet2000/airflow) is a working version (at least with password_auth as backend). I took your meta.yml file as starting point where I just replace the version of flask-login with 2.11. For airflow, I took v1-8-stable branch.

**Comment by sodre** [comment]
I would love to take a PR. would you also like to be added as a maintainer?

**Comment by jpoullet2000** [comment]
I'll probably work on airflow the coming weeks... so I may help if needed. Just let me know. There will probably be a bit of work with 1.8.1 (=> apache).
