### ISSUE TITLE
Airflow has not released 1.10.9 yet.

### ISSUE THREAD

**Issue by atronchi** [conda-forge/airflow-feedstock#42]
1.10.8 was released about a week ago
https://github.com/conda-forge/airflow-feedstock/blob/b8d0a4e89fae650898ebeb8208ec53045b1b623d/recipe/meta.yaml#L2

**Comment by xylar** [comment]
@atronchi, I was concerned about that, see my comment here: https://github.com/conda-forge/airflow-feedstock/pull/41#issuecomment-583687205 

However, conda-forge got triggered when a 1.10.9 release was uploaded to pypi:
https://pypi.org/project/apache-airflow/1.10.9/

I wasn't sure to follow GitHub where there wasn't a 1.10.9 or pypi where there was.

**Comment by xylar** [comment]
If you can confirm, that 1.10.9 was released unintentionally on pypi, we can get the package moved to broken.
