### ISSUE TITLE
Pandas dependency

### ISSUE THREAD

**Issue by clm84** [conda-forge/airflow-feedstock#43]
Hello,

I'm having issues installing airflow in a conda environment alongside pandas 1.0.
Is it possible to adjust the dependency in the recipe? it currently caps <1.0

Thanks

**Comment by xylar** [comment]
@clm84, we take that constrain from upstream:
https://github.com/apache/airflow/blob/1.10.9/setup.py#L482

I don't think we can really second guess their reason for this constraint.  The good news is that their current master has this constraint relaxed to <2.0.0, so you should be in better shape after the next release:
https://github.com/apache/airflow/blob/master/setup.py#L569

**Comment by clm84** [comment]
that makes perfect sense. thanks.

**Comment by clm84** [comment]
Hello,

Hope you are well. sorry to reopen the issue.

I was looking at the latest airflow (1.10.11) and noticed that it has moved to 3.8 and pandas 1.0.5, however the conda recipe is still specifying pandas < 1.0.

https://github.com/apache/airflow/blob/1.10.11/setup.py#L579

https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml#L65

Is this something that can be updated in the conda recipe? Thank you.

**Comment by xylar** [comment]
Oops, sorry, I missed that.  I'll make a new build now.

**Comment by xylar** [comment]
Should be fixed via #48

**Comment by clm84** [comment]
I was able install airflow 1.10.10 with pandas 1.0.5 on python 3.8.
Thank you very much!
