### ISSUE TITLE
Airflow with AWS?

### ISSUE THREAD

**Issue by ericdill** [conda-forge/airflow-feedstock#45]
Are there any blockers to adding the airflow-with-aws packages as outputs of this feedstock? (Technical blockers or social blockers?) My guess is that there's not been a maintainer with a need for the aws bits of airflow, but figured I'd check with you folks first. cc @xylar @sodre

**Comment by sodre** [comment]
No issues on my side!

**Comment by ericdill** [comment]
airflow-aws has dependencies on boto3 and watchtower, requiring the following:
```
    'boto3>=1.12.0,<2.0.0',
    'watchtower~=0.7.3',
```

boto3 should be fine. The [watchtower-feedstock](https://github.com/conda-forge/watchtower-feedstock/pulls) seems unmaintained unfortunately, so I guess I'll need to own that too if i'm going to be adding airflow-with-aws

**Comment by xylar** [comment]
Same, no problem here.  I think we've just been adding support for what folks actually need because it's enough of a headache to maintain what's already there without needlessly adding more.  Best of luck with watchtower.

**Comment by xylar** [comment]
@ericdill, `watchtower` looks like a really light-weight package that should be easy to maintain.  If you're okay with it, I'll put in a PR right now to get us both added as maintainers.  I'll ping you.  Then, we can merge (oldest to newest) all the versions that haven't been added.

**Comment by ericdill** [comment]
@xylar that sounds good. I was going to make sure that I needed the aws stuff before I add a burden here. Still getting airflow up and running on our infrastructure

**Comment by xylar** [comment]
@ericdill, could you go ahead and indicate you would be okay being a maintainer here: https://github.com/conda-forge/watchtower-feedstock/pull/12?  If it turns out you don't need AWS after all, we can always take you off again.

**Comment by xylar** [comment]
closed via #46
