### ISSUE TITLE
Does "with-aws" retire "with-s3"?

### ISSUE THREAD

**Issue by zhangyi-hu** [conda-forge/airflow-feedstock#53]
I found that "with-s3" is no longer here, I'm guessing it is being replaced by "with-aws".

**Comment by xylar** [comment]
@zhangyi-hu, this was changed upstream in 1.10.7, specifically in this commit: https://github.com/apache/airflow/commit/627c40c5ae6a445a4a42b81176744a5f2863f964#diff-2eeaed663bd0d25b7e608891384b7298

I just followed the changes made upstream when I updated dependencies in 1.10.7: https://github.com/conda-forge/airflow-feedstock/commit/9f6cc43eabbef8f19b2c9a1eb1a05598585f85e6#

But, yes, I think the change was just a renaming of `s3` to `aws`.

**Comment by xylar** [comment]
@zhangyi-hu, please close if you feel your question has been addressed.
