### ISSUE TITLE
1.10.12

### ISSUE THREAD

**Issue by afonit** [conda-forge/airflow-feedstock#54]
I have been bit by a bug (I think) in 1.10.**11** and wanted to try out ..12, I see that conda-forge still lists 1.10.**11** https://anaconda.org/conda-forge/airflow instead of what I see here being merged 1.10.**12**

I see this showing a merge for 1.10.**12** ? https://github.com/conda-forge/airflow-feedstock/pull/52

From and end-user perspective, are there posted timelines on (generally) when the conda 1.10.**12** would be available?

**Comment by xylar** [comment]
@afonit, sorry, I completely missed that.  I don't usually check if the final merge works once the testing in the PR passes.  I'll see if I can get it to build correctly.

**Comment by xylar** [comment]
Trying to fix this in #55.  It seems like the version of `celery` used in one of the extensions was missing one if *its* dependencies.  I don't know how this was able to sneak through CI in the PR but not in the merge, but maybe I made a mistake...

**Comment by xylar** [comment]
Give it a couple of hours and it should be available.  @afonit, if you would be willing to close this issue as soon as you are able to successfully install, that would be great.

By the way, I think what happened is that a new version of `vine` was released between when I tested and when I merged, and that version was not compatible with `celery`, so it crashed the merge.

**Comment by afonit** [comment]
It just showed up:
![image](https://user-images.githubusercontent.com/1798497/95379323-3964af00-08b3-11eb-90cc-809f8bd86077.png)
https://anaconda.org/conda-forge/airflow

Thank you.

**Comment by xylar** [comment]
@afonit, just so you know, you won't be able to actually install the package for another half hour to an hour (something to do with how often some server update -- I'm hazy on the details).

**Comment by afonit** [comment]
@xylar yes, it took about a half hour.  My local conda did not see it until about 10 minutes ago - it is installed now.
