### ISSUE TITLE
Airflow 2.0.1

### ISSUE THREAD

**Issue by xylar** [conda-forge/airflow-feedstock#62]
This is just a to-do list and a running commentary on where things are with updating to Airflow 2.0.1.

Issues I've encountered:
* Many extras have moved to standalone packages, one for each "provider" (nearly 60 of them!).  These will have to be added as separate conda-forge recipes, since they update on their own schedules.
* There are still several "extras" that are not providers and these should continue to be handled with `airflow-with-XXX` packages within this feedstock.
* v2.0.0 has some circular dependencies, so it would be difficult to make it work.  There are also some overly restrictive constraints on dependencies for that version that will be hard to satisfy.  I have the impression that skipping to 2.0.1 (released yesterday) is the better option.
* We should create an `apache-airflow` dummy package that points to `airflow`, because the former is the name used on pypi.

To do:
- [x] Get the main `airflow` package working for 2.0.1
- [x] Get the following extras working:   
  - [x]  `apache.atlas`
  - [x] `apache.beam`
  - [x] `apache.webhdfs`
  - [x] `async`
  - [x] `cgroups`
  - [x] `dask`
  - [x] `github_enterprise`
  - [x] `google_auth`
  - [x] `kerberos`
  - [x] `ldap`
  - [x] `password`
  - [x] `rabbitmq`
  - [x] `sentry`
  - [x] `statsd`
  - [x] `tableau`
  - [x] `virtualenv`
- [x] Make dummy packages with deprecated aliases for:
  - [x] `atlas`
  - [x] `webhdfs`
- [x] Make and submit recipes for the following providers that are dependencies:
  - [x] `ftp`
  - [x] `http`
  - [x] `imap`
  - [x] `sqlite`
- [x] Make and submit recipes for the following providers, where dependencies are available:
  - [x] `amazon`
  - [x] `apache.beam`
  - [x] `apache.cassandra`
  - [x] `apache.druid`
  - [x] `apache.hdfs`
  - [x] `apache.hive`
  - [x] `apache.livy`
  - [x] `apache.pig`
  - [x] `apache.spark`
  - [x] `apache.sqoop`
  - [x] `celery`
  - [x] `cloudant`
  - [x] `cncf.kubernetes`
  - [x] `databricks`
  - [x] `datadog`
  - [x] `dingding`
  - [x] `discord`
  - [x] `docker`
  - [x] `exasol`
  - [x] `facebook`
  - [x] `grpc`
  - [x] `hashicorp`
  - [x] `jdbc`
  - [x] `jira`
  - [x] `microsoft.mssql`
  - [x] `microsoft.winrm`
  - [x] `mongo`
  - [x] `mysql`
  - [x] `odbc`
  - [x] `openfaas`
  - [x] `opsgenie`
  - [x] `oracle`
  - [x] `papermill`
  - [x] `plexus`
  - [x] `qubole`
  - [x] `redis`
  - [x] `salesforce`
  - [x] `samba`
  - [x] `segment`
  - [x] `sendgrid`
  - [x] `sftp`
  - [x] `singularity`
  - [x] `snowflake`
  - [x] `ssh`
  - [x] `telegram`
  - [x] `vertica`

Other dependencies:
- [x] `snakebite-py3`
- [x] `pep562`
- [x] `apache-beam`
- [x] `mock<3.0.0`
- [x] `pintodb`
- [x] `kylinpy`
- [x] `azure-batch`
- [x] `azure-kusto-data`
- [x] `azure-mgmt-containerinstance`
- [x] `elasticsearch-dbapi`
- [x] `google-ads`
- [x] `google-cloud-datacatalog`
- [x] `google-cloud-memcache`
- [x] `google-cloud-speech`
- [x] `google-cloud-tasks`
- [x] `google-cloud-workflows`
- [x] `neo4j`
- [x] `pdpyras`
- [x] `presto-python-client`
- [x] `python-jenkins` (pip check issue conda-forge/python-jenkins-feedstock#7)
- [x] `slack-sdk`
- [x] `yandexcloud`
- [x] `zdesk`

Make and submit recipes for the following providers, where dependencies are not yet available or have issues:
  - [x] `apache.kylin`
  - [x] `apache.pinot`
  - [x] `elasticsearch`
  - [x] `jenkins`
  - [x] `microsoft.azure`
  - [x] `google`
  - [x] `neo4j`
  - [x] `pagerduty`
  - [x] `presto`
  - [x] `postgres`
  - [x] `slack`
  - [x] `yandex`
  - [x] `zendesk`

Feedstocks that exist but need attention:
- [x] https://github.com/conda-forge/azure-common-feedstock

**Comment by xylar** [comment]
`apache.beam` requires `apache-beam`, which requires `mock<3.0.0`, which I'm working on here: https://github.com/conda-forge/mock-feedstock/pull/33

**Comment by xylar** [comment]
`mock` is taken care of, working on `apache-beam`: https://github.com/conda-forge/apache-beam-feedstock and `crcmod`: https://github.com/conda-forge/crcmod-feedstock/pull/10

**Comment by xylar** [comment]
`apache.webhdfs` appears to require `apache-airflow-providers-hdfs`.

**Comment by xylar** [comment]
Recipe for `pep562` submitted: https://github.com/conda-forge/staged-recipes/pull/13940

**Comment by xylar** [comment]
Recipe for `snakebite-py3` submitted: https://github.com/conda-forge/staged-recipes/pull/13942

**Comment by xylar** [comment]
Recipes for the `ftp`, `http`, `imap` and `sqlite` providers submitted: https://github.com/conda-forge/staged-recipes/pull/13958

**Comment by xylar** [comment]
`connexion` is failing `pip check` because of bad version metadata.  A PR to update the source to come from `pypi`, which has the right version, is here: https://github.com/conda-forge/connexion-feedstock/pull/21

**Comment by xylar** [comment]
There is an issue with `pip check` and `typing` that needs to get figured out if we're going to use `pip check` for these packages: https://github.com/conda-forge/typing-feedstock/issues/30

Since `typing` isn't a requirement for py>=37, I think this probalby only affects py 36.

**Comment by xylar** [comment]
Trouble with dependencies in for `python-jenkins`: https://github.com/conda-forge/python-jenkins-feedstock/pull/7

**Comment by xylar** [comment]
`apache-airflow-providers-mysql` requires `mysqlclient >=1.3.6,<1.4`, which is only available for `python <= 3.6`.  Attempts appear to have been made to update this without success (so far at least):
https://github.com/apache/airflow/issues/8292
https://github.com/apache/airflow/pull/12688

**Comment by xylar** [comment]
Next round of provider recipes has gone in:
https://github.com/conda-forge/staged-recipes/pull/13988

**Comment by xylar** [comment]
Well, I'm now the maintainer of about 100 additional feedstocks (not an exaggeration) but this is done!

**Comment by tazimmerman** [comment]
@xylar This is looong overdue, but thank you for your effort. I'm a happy airflow 2.x user, all because of you! :)

**Comment by xylar** [comment]
I appreciate hearing that!  It's a lot of work and since it's not a package I use myself, it's hard to know whether it's working well for folks.  Keep me posted if trouble emerges.
