### ISSUE TITLE
airflow-with-dask for python 3.9+

### ISSUE THREAD

**Issue by mison6** [conda-forge/airflow-feedstock#89]
### Comment:

Is it possible to create an airflow-with-dask build for python >= 3.9?

I see the comment that distributed<2.20 doesn't support python 3.9, but newer versions do. Could there be a second airflow-with-dask entry added to meta.yaml specifically for python >= 3.9, with updated constraint on dask and distributed? I'm not familiar enough with meta.yaml to know if/how that might work.

**Comment by xylar** [comment]
@mison6, sorry about that.  I missed that constraint when I updated awhile back.  You're definitely right that the constraint is no longer needed.  Should be fixed in #90
